development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: rails-chat-tutorial_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %> # redis://localhost:6379/1
  channel_prefix: <%= ENV["REDIS_PREFIX"] %> #rails-chat-tutorial_production
